### ISSUE TITLE
Структура БД , использование liquibase в проекте

### ISSUE THREAD

**Issue by SlaykSD** [OurBookStore/TheBookStore#5]
Необходимо определится с минорной версией структуры базы данных  и решить: пользуемся hibernate для автосоздания таблиц или нет.

**Comment by alekseiiagnenkov** [comment]
Не уверен, что нам нужен liquibase, так как у hibernate есть автогенерация. liquibase может понадобиться для наполнения базу какими то данными, но думаю это понадобится еще не скоро

**Comment by SlaykSD** [comment]
![image](https://github.com/OurBookStore/TheBookStore/assets/60920077/5a67cef0-9d5c-411e-9000-970302f5f61a)
Структура БД

**Comment by SlaykSD** [comment]
ID думаю можно bigint, nickname, email, pasword, name(book) , имена автора varchar, int для price, count, number_orders, bigint для дат
